name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: tododb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Backend install + test
      - name: Install backend deps
        run: |
          cd backend
          npm ci

      - name: Run backend tests
        run: |
          cd backend
          DB_HOST=localhost \
          DB_PORT=5432 \
          DB_USER=postgres \
          DB_PASSWORD=postgres \
          DB_NAME=tododb \
          npm test

      # Build Docker images
      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/devops-backend ./backend

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/devops-frontend ./frontend

      # Login Docker Hub
      - name: Login DockerHub
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      # Push images
      - name: Push backend
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/devops-backend

      - name: Push frontend
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/devops-frontend
          deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/devops-project
            git pull origin main
            docker compose pull
            docker compose up -d