name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  # =============================
  # 🔧 BUILD & TEST (CI)
  # =============================
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: tododb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # ===== BACKEND =====
      - name: Install backend deps
        run: |
          cd backend
          npm ci

      - name: Run backend tests
        run: |
          cd backend
          npm test
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: tododb
          DB_USER: postgres
          DB_PASSWORD: postgres

      # ===== FRONTEND =====
      - name: Install frontend deps
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # ===== DOCKER BUILD =====
      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_GR3 }}/todo-frontend ./frontend
          docker build -t ${{ secrets.DOCKER_HUB_GR3 }}/todo-backend ./backend

      # ===== LOGIN DOCKER HUB =====
      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_KHAITUNGMINH }}" | docker login -u "${{ secrets.DOCKER_HUB_GR3 }}" --password-stdin

      # ===== PUSH DOCKER =====
      - name: Push images
        run: |
          docker push ${{ secrets.DOCKER_HUB_GR3 }}/todo-frontend
          docker push ${{ secrets.DOCKER_HUB_GR3 }}/todo-backend

  # =============================
  # 🚀 DEPLOY (CD)
  # =============================
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    # CHỈ deploy khi push vào main
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/devops-project-hcm-group3
            git pull origin main
            docker compose down
            docker compose pull
            docker compose up -d --build